modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "AvocadoSpud, DigitalPear"
credits = "ebo2022"
description = "A small mod that adds a biome to the world."

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.4.9,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${id}]]
modId = "terrablender"
mandatory = true
versionRange = "[1.1.0.101,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "carpenter"
mandatory = false
versionRange = "[1.1.1,)"
ordering = "AFTER"
side = "BOTH"